# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: "GRFC9HYN3S",
      issuer_id: "4a594785-b4ff-40e5-97d0-c326be294e8c",
      key_filepath: File.join(Dir.pwd, "GRFC9HYN3S.p8")
      
    )
    previous_build_number = latest_testflight_build_number
    current_build_number = previous_build_number + 1
    increment_build_number(xcodeproj: "Runner.xcodeproj",
      build_number: current_build_number
    )
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
